//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.VENTAs = new HashSet<VENTA>();
        }
    
        public int NUMERO_MOTOR { get; set; }
        public string MODELO { get; set; }
        public int ID_MARCA { get; set; }
        public int NUMERO_PUERTA { get; set; }
        public string COMBUSTIBLE { get; set; }
        public string COLOR { get; set; }
        public int ID_AGENCIA { get; set; }

        [JsonIgnore]
        public virtual AGENCIA AGENCIA { get; set; }
        [JsonIgnore]
        public virtual MARCA MARCA { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA> VENTAs { get; set; }
    }
}
